### ISSUE TITLE
Training 

### ISSUE THREAD

**Issue by efyphil** [NVlabs/learningrigidity#1]
Good morning, thank you for work. Do you have any code for training rigidity network?

**Comment by lvzhaoyang** [comment]
Hi, thanks for the interest. Yes, we will release it. Just due to my schedule constraints for the CVPR submission, this release plan is slightly behind. I will update it soon after CVPR deadline, Nov 15. 

If you need something about training in this project soon for your CVPR, please drop me an email. I will be glad to help.

**Comment by efyphil** [comment]
Thank you for fast answer.
